<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Account;
use AppBundle\Entity\Licence;

/**
 * AccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountRepository extends BaseRepository
{
    public function create(Account $account, Licence $licence, $amount)
    {
        // TODO: Change password hashing and generation
        $current = new \DateTime();
        $account->setCreated($current)
          ->setModified($current)
          ->setAmount($amount)
          ->setLicence($licence->reduceRemaining(1));
        $this->save($account);
    }

    public function accountExists($email, $licenceType)
    {
        $account = $this->findOneBy(['email' => $email]);

        return $account && $account->getLicence()->getType() == $licenceType;
    }
}
