<?php

namespace AppBundle\Repository;

use AppBundle\Billing\Purchase;
use AppBundle\Entity\Account;
use AppBundle\Entity\Licence;

/**
 * AccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountRepository extends BaseRepository
{
    public function createFromPurchase(Purchase $purchase)
    {
        // TODO: Change password hashing and generation
        $current = new \DateTime();
        $purchase->account()->setCreated($current)
          ->setModified($current)
          ->setAmount($purchase->totalCost())
          ->setLicence($purchase->article()->reduceRemaining(1));
        $this->save($purchase->account());
    }

    public function accountExists($email, $licenceType)
    {
        $account = $this->findOneBy(['email' => $email]);

        return $account && $account->getLicence()->getType() == $licenceType;
    }
}
