<?php

namespace AppBundle\Repository;

/**
 * ProverbRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProverbRepository extends BaseRepository
{
    public function published(int $proverbId = null)
    {
        $queryBuilder = $this->createQueryBuilder('Proverb')
             ->select('proverb')
             ->from('AppBundle:Proverb', 'proverb')
             ->where('proverb.published IS NOT NULL');

        if ($proverbId) {
            $queryBuilder->andWhere('proverb.id = :id')->setParameter('id', $proverbId);
        }
        return $queryBuilder;
    }
}
