<?php

namespace AppBundle\Repository;

/**
 * ProverbRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProverbRepository extends BaseRepository
{
    public function published()
    {
        return $this->createQueryBuilder('Proverb')
          ->select('proverb')
          ->from('AppBundle:Proverb', 'proverb')
          ->where('proverb.published IS NOT NULL');
    }
}
